### ISSUE TITLE
Incorrect explorer url

### ISSUE THREAD

**Issue by xuanyan0x7c7** [QtumLightProject/qtum-light-wallet#2]
The domain should be https://qtum.info/

https://github.com/QtumLightProject/qtum-light-wallet/blob/e00bf86da5e877df40f49fc8d3e16fe8ab7d1a8d/src/App.js#L568

**Comment by bobio2018** [comment]
@xuanyan0x7c7  thank you, this address is now fixed. 
please note contract interaction is not turned on for mainnet, we will update it and release a new version in the near future.
